server:
  port: ${PORT:80}

spring:
  rabbitmq: # mq 配置
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /v-shop
  redis:  # redis配置
    host: 127.0.0.1
    port: 6380
    password:
    database: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 暴露健康检查的端点
